### ISSUE TITLE
Fail early with an appropriate error message if not on AWS EC2

### ISSUE THREAD

**Issue by mtpereira** [errm/ekstrap#31]
Currently, running `ekstrap` outside of AWS EC2 returns the following error message:

```
2018/06/25 19:29:45 InvalidEndpointURL: invalid endpoint uri                                                                                                                
caused by: parse https://ec2.<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
        <meta content="no-cache" http-equiv="Pragma" />
        <title>Waiting...</title>
        <script type="text/javascript">
            var pageName = '/';
            top.location.replace(pageName);
        </script>
    </head>
    <body></body>
.amazonaws.com/: invalid character " " in host name
```

It probably should check if it is running on EC2 and fail with an error message in the vein of "Running outside of EC2, cannot configure node.'

**Comment by errm** [comment]
Interesting on my system I see an error like

```
2018/06/26 08:17:27 RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/placement/availability-zone: EOF
```

It seems on your system something responds to the metadata service ip...
Other than a request to this endpoint timing out how can we detect if we are on an AWS instance or not?

**Comment by mtpereira** [comment]
This happened on a CentOS and a Debian docker container, just by running ekstrap as root.
We could follow this and check the contents of `/sys/hypervisor/uuid`: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html

**Comment by errm** [comment]
Humm seems complicated ...

perhaps we could just add some validation that the thing returned here looks like an aws region https://github.com/errm/ekstrap/blob/master/main.go#L38-L44

And also return a better error message if the call to the metadata endpoint times out ...

**Comment by mtpereira** [comment]
Why do you feel it is complicated? It seems to be just checking the first 3 chars of a file. Might be annoying to test but should be easy to implement, right?

**Comment by errm** [comment]
There seemed to be some cases where /sys/hypervisor/uuid wouldn't be reliable ...

>  Furthermore, for EC2 instances that are not using Amazon Linux, the distribution's implementation of SMBIOS might represent the UUID in little-endian format, therefore the "EC2" characters do not appear at the beginning of the UUID.

It seems overkill to test this, when it might stop the tool from working when it would otherwise work perfectly fine ....

Perhaps we can just capture the errors in https://github.com/errm/ekstrap/blob/master/main.go#L38-L44 and just make a better error message ...

**Comment by mtpereira** [comment]
Sounds good!
